#!/bin/bash

function update_system() {
  yay -Syu --answerclean All --answerdiff None --nocleanmenu --nodiffmenu --save --noconfirm
  sudo snap refresh
  sudo pacman -Syyu
}
export -f update_system
echo "update_system"

function update_system_hard(){
  sudo pacman-mirrors -c all
  yay -Syu --answerclean All --answerdiff None --nocleanmenu --nodiffmenu --save --noconfirm
  sudo snap refresh
  sudo pacman -Syyu
}
export -f update_system_hard
echo "update_system_hard"

function update_chrome(){
  yay -S google-chrome --answerclean All --answerdiff None --nocleanmenu --nodiffmenu
}
export -f update_chrome
echo "update_chrome"

function clean_system(){
  sudo paccache -rvk0
}
export -f clean_system
echo "clean_system"
