apiVersion: v1
kind: Pod
metadata:
  name: vpn-downloader
  labels:
    group: vpn-downloader
spec:
  containers:
    - name: gluetun
      image: ghcr.io/qdm12/gluetun
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      resources:
        limits:
          memory: "512Mi"
          cpu: "2000m"
        requests:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: vpn-downloader-secrets
              key: OPENVPN_USER
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpn-downloader-secrets
              key: OPENVPN_PASSWORD
        - name: VPN_SERVICE_PROVIDER
          value: "private internet access"
        - name: SERVER_REGIONS
          value: "Netherlands"
        - name: FIREWALL
          value: "on"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "192.168.1.0/24"
      volumeMounts:
        - name: tun-device
          mountPath: /dev/net/tun

    - name: transmission
      image: lscr.io/linuxserver/transmission
      resources:
        limits:
          memory: "1Gi"
          cpu: "2000m"
        requests:
          memory: "256Mi"
          cpu: "500m"
      env:
        - name: USER
          value: "simjeeh"
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: vpn-downloader-secrets
              key: TRANSMISSION_RPC_PASSWORD
        - name: TZ
          value: "America/Los_Angeles"
      ports:
        - containerPort: 9091
          hostPort: 9091
          protocol: TCP
      volumeMounts:
        - name: downloads
          mountPath: /downloads
        - name: config
          mountPath: /config

  volumes:
    - name: tun-device
      hostPath:
        path: /dev/net/tun
        type: CharDevice
    - name: downloads
      hostPath:
        path: /mnt/podman/vpn-downloader/.data/downloads
        type: DirectoryOrCreate
    - name: config
      hostPath:
        path: /mnt/podman/vpn-downloader/.data/config
        type: DirectoryOrCreate
